### PR TITLE
docker-machine info

### LINKED ISSUE #136: Document docker-machine use
Include an explanation of docker-machine in README.

### PR DESCRIPTION
**Pull request by julienchastang**
closes #136. @isuftin tackling low-hanging fruit first. OK with you? You are the author, BTW :-)

### CODE REVIEW

**Comment by julienchastang** [comment]
Travis failure is false negative, BTW.

**Comment by isuftin** [comment]
@julienchastang This PR should probably be pulled in after the other changes are made since I don't think it will be valid with the state of the project as it stands in canonical.

**Comment by julienchastang** [comment]
@isuftin I believe this documentation (which only effect the `README.md` and no code) is independent of what comes next and is useful. I use `docker-machine` on my OS X laptop currently for this project for experimentation and testing. I assume you do as well. If you are OK with the content, I'll merge it in and move on to the next issues we discussed.

**Comment by isuftin** [comment]
@julienchastang That's cool with me. I guess everything will come together for the next tagged release of the Docker project

**Pull request merged**
