### PR TITLE
4.6.15

### PR DESCRIPTION
**Pull request by julienchastang**
----

#

### CODE REVIEW

**Comment by julienchastang** [comment]
ping @lesserwhirls

**Comment by lesserwhirls** [comment]
Looks great - thank you Julien!

**Comment by lesserwhirls** [comment]
Mind if I merge it in?

**Comment by julienchastang** [comment]
Go for it!

**Comment by julienchastang** [comment]
@lesserwhirls You'll also find the following up-to-date with respect to this change:

- https://hub.docker.com/repository/docker/unidata/thredds-docker (v4.6.15 now available)
- https://tds.scigw.unidata.ucar.edu
- http://thredds-aws.unidata.ucar.edu/thredds/catalog.html

**Pull request merged**
