### PR TITLE
Added configuration to be able to run THREDDS in a simple Docker Swarm configuration

### PR DESCRIPTION
**Pull request by isuftin**
I've added a new compose file specific to allowing THREDDS to run in Docker Swarm. This is in preparation for work I will be doing with this container in a clustering workflow. I've also updated the README to include instructions for how this works.

### CODE REVIEW

**Comment by julienchastang** [comment]
Thanks for this. The problem is the top-level `README.md` is sort of getting unwieldy (related #150), and may simply belong in its own `README` e.g., `README-SWARM.md` or some such. Or maybe its own directory `swarm/README.md` and `swarm/docker-compose-swarm.yml`.

**Comment by isuftin** [comment]
@julienchastang I can certainly make a swarm-specific README. However, the swarm config does use the same files tat the other compose file uses in the top level dir under files/ as well as other directories the end user may wish to use. Putting the compose file in a subdirectory does raise some complexity in terms of having it move directory levels up/down to find required files. So leaving the compose file at the top level makes more sense here. By default, docker-compose will not use this file so it's not in danger of getting used unknowingly. You'll have to specify it explicitly for stakc deploys. 

So should I just break out the swarm config into its own README and just link it from the main README?

**Comment by julienchastang** [comment]
OK, thanks for the explanation. Can anything be done concerning the usgs specific labeling in `docker-compose-swarm.yml` file?

**Comment by isuftin** [comment]
@julienchastang hah yes of course :) I will update that tomorrow.

Also, which direction did you want me to take? Just split out the README?

**Comment by isuftin** [comment]
@julienchastang I've split out the README by adding a Swarm specific README. I've also removed the USGS specific labeling from the docker volume in the swarm compose configuration

**Comment by isuftin** [comment]
@julienchastang I've also moved the tomcat-users configuration into a `secrets` configuration so that in a swarm, the data within the file as it's set on the container is encrypted

**Comment by julienchastang** [comment]
@isuftin Are we good here? All your work was merged in #170.

**Pull request closed without merging**
