### PR TITLE
Download ncSOS from GitHub

### PR DESCRIPTION
**Pull request by isuftin**

### CODE REVIEW

**Comment by isuftin** [comment]
Solves https://github.com/Unidata/thredds-docker/issues/69

**Comment by isuftin** [comment]
I've updated to ncsos 1.3 here because previous to 1.3, the github repo for this jar was putting the jar into a zip and having that set up for release. We can work with that but it complicates the installation procedure in the Dockerfile. If 1.3 of ncsos works as well as 1.2.1 for this build, we should go with that because with 1.3 and beyond, they make the jar itself available.

**Comment by julienchastang** [comment]
Because @lesserwhirls comment on #69  concerning ncsos being included in the next release of the TDS (both 4.6 and 5.0), I plan on closing this. OK with you @isuftin or do we need this PR as a stopgap solution?

**Comment by isuftin** [comment]
@julienchastang May as well pull it in while you're not at  4.6/5.0 yet. Just make sure ncsos 1.3 works with this setup

**Comment by julienchastang** [comment]
Alright. We'll do.

**Comment by julienchastang** [comment]
Closed by #147

**Pull request closed without merging**
