### PR TITLE
libnetcdf

### LINKED ISSUE #87: Add libnetcdf for NetCDF-4 writing in NCSS
Instructions for how to build NetCDF-4 can be found [here](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html). A good way to test that it's working is to open a dataset's NCSS page and attempt to download the result of the query as NetCDF-4.

### PR DESCRIPTION
**Pull request by julienchastang**
closes #87 

@cwardgar This will probably take a couple of iterations to get right, but at least it builds :-) @WardF Does the netcdf build look kosher?

### CODE REVIEW

**Comment by WardF** [comment]
It should work, although the hdf5 version is pretty old.  I wasn't actually aware that we maintained versions of dependencies on Unidata servers.  We should upload and install the latest hdf5 version, or you can modify to pull direct from the HDF5 server.

For example, in the `Dockerfile.base` and `Dockerfile.serial` config files (found in the https://github.com/docker-nctests project under the `tests-regression` directory, you can see how we download and install hdf5)

You can also see, in the `run_serial_tests.sh` script in the same project/directory, how we build netcdf-c with both autotools and cmake.  Some of the options used in this script, like `--enable-threadsafe` and `--with-pthread` don't correspond to options available in netcdf-c.  

## Dockerfile.base

````
ENV HDF5VER 1.8.17
ENV HDF5_VER hdf5-${HDF5VER}
ENV HDF5_FILE ${HDF5_VER}.tar.bz2
RUN wget http://www.hdfgroup.org/ftp/HDF5/releases/${HDF5_VER}/src/${HDF5_FILE}
RUN tar -jxf ${HDF5_FILE}
````

## Dockerfile.serial

````
RUN cd ${HDF5_VER} && ./configure --disable-static --enable-shared --disable-fortran --enable-hl --prefix=/usr --with-szlib && make install -j 4
````

**Comment by cwardgar** [comment]
The configuration mentioned [here](http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/netcdf4Clibrary.html#installation_linux_source_build):
```
./configure --with-zlib=${ZDIR} --prefix=${H5DIR} --enable-threadsafe --with-pthread=${PDIR} --enable-unsupported
```
applies to hdf5. netcdf should be built as described in the docs.

**Comment by julienchastang** [comment]
@cwardgar thxs for the clarification

**Comment by julienchastang** [comment]
This instance of the TDS is running with the `thredds-docker`, `libnetcdf` branch.

<http://unicloud.westus.cloudapp.azure.com/thredds/catalog/catalog.html>

@cwardgar @lesserwhirls I believe netCDF4 capability is in place as evidenced by the `netcdf4` output format option for NCSS. For example,

<http://unicloud.westus.cloudapp.azure.com/thredds/ncss/grib/NCEP/GFS/Global_onedeg/GFS_Global_onedeg_20161023_1800.grib2/dataset.html>

Can you confirm netCDF4 capability is working?

@WardF One more question: Is any part of the netcdf build superfluous? I'm thinking `szip` build may be unnecessary.

Thanks everyone. I think we are on the home stretch.

**Comment by cwardgar** [comment]
Yep, libnetcdf is being loaded successfully.

**Pull request merged**
