### PR TITLE
Updates to both TDM and THREDDS and Compose config

### PR DESCRIPTION
**Pull request by isuftin**
Note that inn order for the compose configuration changes to make sense, the available Docker containers would need to have a new version cut after being built and the Compose image tags for both containers would need to be increments to point to those.

### CODE REVIEW

**Comment by julienchastang** [comment]
@isuftin Thanks for all your hard work here. Would it be possible to separate these out into individual compartmentalized pull requests with ideally one commit and no merge commits? I think github, open-source collaborations and my brain work best when I have to look at the smallest possible change set corresponding to a given problem. Otherwise, I don't what change is related to what other change and it is difficult for me to tease what is going on. Ideally, you would open variety of issues corresponding to the problems you have found and then send a PRs that address and eventually close those issues. Thanks again.

**Comment by isuftin** [comment]
@julienchastang I can try to do that. Unfortunately, a lot of these changes are interrelated so it may get a bit weird but I'll try to steer through it. 

Also, would you mind creating a new Github project called thredds-tdm-docker so we can break out the TDM stuff into its own? The coupling with the THREDDS Docker stuff doesn't seem to have purpose as the two containers don't really depend on one another.

**Comment by julienchastang** [comment]
@isuftin Thanks. I did not know about compose environment variables. This avenue provides a nice way to parameterize containers. Also documenting docker-machine is a good idea. I've started pulling these changes apart. See #136 and #137. If possible please avoid superfluous changes like end of line spaces. (I'm not saying it is not a problem, but simply keep them in their own change set so the diff is easier to read and understand.)  We can deal with `CHANGELOG.md` later. I thought about pulling the TDM into its own Docker project when we started the `thredds-docker` project, but at the time I felt like it was unwieldy to have a bunch of small Docker projects. We might revisit this decision when things are a bit more stable.

**Comment by isuftin** [comment]
@julienchastang This looks good, I can continue the process of creating issues and feature branch pr to them

**Pull request closed without merging**
