### PR TITLE
more direct wait for service

### PR DESCRIPTION
**Pull request by gajowi**
loop and wait for short time rather than a static 300s

### CODE REVIEW

**Comment by gajowi** [comment]
adresses #111

**Comment by julienchastang** [comment]
Can you describe a bit more about what `nc` and the `for` loop is doing?

Also, I would squash all these commits into one commit on your local ` gajowi-travis-wait8080 ` branch, have a nice, concise git log message,  and force push this branch to  ` gajowi/thredds-docker`. You can give this a shot or I can do it for you (I will preserve author attribution, in that case). Let me know.

**Comment by gajowi** [comment]
The nc -z command waits for a port to be opened, scanning without sending data as such. The -w option adds a timeout.  It seemed a simpler, more direct test that a http get, but it turns out that tomcat can have opened the port but still be unresponsive for some time so the test is not sufficient - and therefore not really needed. I kept it in any case on principle because it is good to be able to distinguish between different sorts of failure.
The bash for loop is trying a http get 5 times with a 15s sleep between tries (and after the final try if it gets that far). So far I've observed tests waiting once for 15s each time, so it is not ready immediately after the nc success but ready within 15s.
I guess it may be fragile to use a bash for loop in this travis context as they might change the travis implementation but I'd expect it to be pretty reliable and an easy error to catch if the situation changes later. Use of nc in this way seems pretty broad.
I'll have to figure out how to squash the commits in this context. My reading on the topic suggests I should not do this if I've committed then to a shared repo - but I guess my fork does not count.  I'll be interested to see how my fork keeps tracking the main project if I force push to my fork master and redo the PR from there.  In any case, my fork only has content I want to submit, so if I delete it and re-fork, nothing much is lost, except perhaps the existing PRs might get references broken. I'm mostly happy to give that a go - but I'd have been happier if you just said 'great I'll grab those changes - thanks for contributing as a PR and making it easy for me' :-P. I guess sharing is not easy - we all like to hold control over what we can.

**Comment by gajowi** [comment]
According to https://help.github.com/articles/configuring-commit-squashing-for-pull-requests/ as I interpret, you can configure the project to allow/enable squashing commits at the point of accepting a PR. That would make contributing easier though the resultant topic/message might be ugly. Want to try?

**Comment by julienchastang** [comment]
closed by #113

**Pull request closed without merging**
