### PR TITLE
Create LICENSE.txt

### LINKED ISSUE #86: licensing
I'm working on releasing a hyrax docker project and just realised I've copied significantly from this project. (especially as I'm using the same underlying tomcat container) Before I release I'd like to be clear on licensing.  I'm currently planning on applying a cc-by license, treating the content as predominantly configuration data and instructions, rather than being original software, but I could change to an MIT license. In any case it would help for it to be clear how this project is licensed. I think attributing it is clear, with a link to the github site and an indicative date.

I'm hoping/expecting you are happy to provide a permissive license. Github has advice at: https://github.com/blog/1530-choosing-an-open-source-license

### PR DESCRIPTION
**Pull request by lesserwhirls**
closes #86

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Don't merge yet...

**Comment by lesserwhirls** [comment]
ok, now we're good.

**Comment by lesserwhirls** [comment]
Feedback from @julienchastang @dopplershift @ethanrd?

**Comment by ethanrd** [comment]
Yes, BSD 3-clause for this project seems like the way to go.

**Comment by julienchastang** [comment]
@lesserwhirls Thanks! Is it OK if I squash into one commit. Sorry, I am kind of OCD about these things :-) Thanks again.

**Comment by lesserwhirls** [comment]
Let's hold off for just a bit on this. There is one open question that
needs to be resolved before we merge it in.

**Comment by julienchastang** [comment]
@lesserwhirls Sounds good. You are in the driver's seat for this one. :-) I'll let you do the merge.

**Comment by lesserwhirls** [comment]
Ugly merge history due to going through github interface to merge, update, etc. Closing and making new PR.

**Comment by dopplershift** [comment]
FYI, if you can rebase when you merge through the web UI, all of that ugliness will go away.

**Comment by lesserwhirls** [comment]
I thought that was an option. I didn't see it but 'll look more closely next time.

**Comment by dopplershift** [comment]
Double check that it's enabled under the repository settings.

**Comment by dopplershift** [comment]
And also, come to think of it, you could have done the rebase locally and force pushed. There's never a reason to re-make a PR, unless you're changing the "owner" so to speak.

**Comment by lesserwhirls** [comment]
I don't have permissions on this repo - @julienchastang, can you check?

**Comment by julienchastang** [comment]
@lesserwhirls I believe you have write permissions for this repo:
permissions

And yes, @dopplershift taught me the trick of squashing and force pushing PR branches.

**Comment by lesserwhirls** [comment]
Yep, but you need admin to check the settings to see if rebasing via the github web interface is enabled.

**Comment by julienchastang** [comment]
Ahh, OK you were trying to rebase via github. Yes, what I meant was, squash, rebase, etc. **locally** and force push your PR branch. What's cool is travis etc. recognizes this situation a reruns the tests, and so forth. And since it is just a PR branch, no one cares or will be harmed by the force push. Remarkably,  it all just works.

**Comment by dopplershift** [comment]
I forgot, I can check--and rebasing from the web UI is enabled. Next time you go to merge, click the downward triangle next to the green button. You can then select "Rebase and Merge".

**Pull request closed without merging**
