### PR TITLE
tdm moving to its own repo unidata/tdm-docker

### LINKED ISSUE #138: Put the TDM in its Own Docker Project Repo
Consider putting the TDM in its own Docker Project Repo. This would simplify things especially on the [thredds-docker dockerhub page](https://hub.docker.com/r/unidata/thredds-docker/) at the expense of a new repository.

### PR DESCRIPTION
**Pull request by julienchastang**
closes #138

### CODE REVIEW

**Comment by isuftin** [comment]
👍 

I've begun working with the tdm-docker repo. We can start removing the tdm docker stuff from  this repo immediately

**Comment by isuftin** [comment]
Once #140 and #141 are pulled into canonical, it should be simple to create a new feature branch that removes the TDM stuff out of this repo

**Comment by isuftin** [comment]
@julienchastang I would actually keep the TDM stuff in the compose file. You can update the image name/tag to point to the TDM Docker image from the new repo. But this would allow end users to use the TDM container against the Thredds Docker container without having to go to lengths to bring the two together. You can just note that it's optional to run the tdm container.

**Comment by julienchastang** [comment]
@isuftin For downstream PRs that are effected by this PR, you actually don't even need to create new branches or PRs. On your end, you can fix your branch (by rebasing, resetting, etc. -- fixing/rewriting the commit history) and subsequently *force* push onto your feature branch. Travis/CI will even figure this out and redo the Travis/CI run. I do this all the time, and is quite convenient. It avoids excessive PRs in these sorts of scenarios.

Noted about keeping some TDM stuff around. Sooo, what I am going to do is fix my local branch and force push in the manner I just described essentially fixing this PR without having to create a new one.

**Comment by julienchastang** [comment]
@isuftin How does this look now? Ready to merge?

**Comment by isuftin** [comment]
👍  We probably will want to re-add the instructions to run TDM container from this compose file but that can be re-added later once everything settles down a bit and we have everything in place

**Comment by julienchastang** [comment]
I thought about preserving those instructions but the problem is that the `tdm-docker` repo will have the same instructions and I don't like maintaining duplicate documentation. Nevertheless, it seems like the `README.md` should have a pointer to the TDM repo beyond the note that I added at the top, especially if the `docker-compose.yml` mentions it. I will add something to this effect.

**Comment by isuftin** [comment]
@julienchastang Seems fair to me

**Pull request merged**
