### PR TITLE
4.6.11

### LINKED ISSUE #176: Update Reference to Nexus Artifacts in Dockerfile
per @lesserwhirls 

use 

```
https://artifacts.unidata.ucar.edu/repository
```

instead of

```
https://artifacts.unidata.ucar.edu/content/repositories
```

### LINKED ISSUE #178: 4.6.11
TDS 4.6.11 is out

### PR DESCRIPTION
**Pull request by julienchastang**
closes #176 and #178. Might take a few iterations before getting this PR right.

### CODE REVIEW

**Comment by julienchastang** [comment]
@isuftin is dockerswarm ready to go as far as this `4.6.11` release is concerned?

**Comment by julienchastang** [comment]
[http://thredds-jetstream.unidata.ucar.edu/thredds/catalog.html](http://thredds-jetstream.unidata.ucar.edu/thredds/catalog.html) seems to work OK with `4.6.11`.

**Comment by isuftin** [comment]
@julienchastang I'll give it a try today to make sure. What we'll probably need to do is update here:

- https://github.com/Unidata/thredds-docker/blob/master/docker-compose-swarm.yml#L23
- https://github.com/Unidata/thredds-docker/blob/master/docker-compose.yml#L5
- https://github.com/Unidata/thredds-docker/blob/master/docker-compose.yml#L12

We won't be able to do so until those updated images exist.

I will test by building 4.6.11 locally and then testing it via swarm. If the regular container works fine I see no reason that it shouldn't work within the swarm.

**Comment by isuftin** [comment]
@julienchastang 

```
...
thredds_thredds.1.a7oy083g6t5s@worker3    | 07-Dec-2017 15:23:05.152 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 21165 ms
...


$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                           PORTS
h2zgq56vmv6p        thredds_thredds     replicated          1/1                 unidata/thredds-docker:4.6.11   *:80->8080/tcp,*:443->8443/tcp,*:8443->8443/tcp
```

👍

**Pull request merged**
