### PR TITLE
Added a health check to the Dockerfile

### PR DESCRIPTION
**Pull request by isuftin**

### CODE REVIEW

**Comment by julienchastang** [comment]
Thanks @isuftin for the PR. Would it be possible to have some details of what this is? Thanks again.

**Comment by isuftin** [comment]
@julienchastang Sure. What this PR provides is a health check for the Docker container. 

https://docs.docker.com/engine/reference/builder/#healthcheck

After 60 seconds (an every 60 seconds afterwards) the container will attempt to curl `http://localhost:8080/thredds/catalog.html` from within itself and expect a 200 HTTP response. If it gets that, the container is marked as healthy for when you perform `docker ps`. If the code is not 200, the container is marked as not healthy and the user can then perform diagnostics or launch another container.

https://blog.alexellis.io/test-drive-healthcheck/

**Comment by julienchastang** [comment]
@isuftin can you clean up the commit history by rebasing off of `origin/master` and force pushing to your `isuftin:HEALTHCHECK` branch?

**Comment by isuftin** [comment]
@julienchastang Are you instead going to use https://github.com/Unidata/thredds-docker/pull/169 ?

**Comment by julienchastang** [comment]
Yes, #166 has an out-of-date commit history.

**Comment by julienchastang** [comment]
closed by #169

**Pull request closed without merging**
